version: '3.9'

networks:
  local_net_more:

services:
  web:
    container_name: nginx-latest
    build:
      context: .
    volumes:
      - ./src:/var/www/html
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_PORT_TLS:-443}:443"
    networks:
      - local_net_more


